load("@crates//:defs.bzl", "all_crate_deps")
load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "rinx_analyzer",
    srcs = glob(["src/**/*.rs"]),
    edition = "2024",
    visibility = ["//visibility:public"],
    deps = all_crate_deps(
        normal = True,
    ) + [
        "//crates/ast:rinx_ast",
        "//crates/entity:rinx_entity",
        "//crates/filter:rinx_filter",
        "//crates/toctree:rinx_toctree",
        "//crates/index:rinx_index",
        "//crates/scope:rinx_scope",
    ],
)
