[package]
name = "rinx_analyzer"
version = "0.1.0"
edition.workspace = true

[dependencies]
rinx_ast = { path = "../ast" }
rinx_entity = { path = "../entity" }
rinx_filter = { path = "../filter" }
rinx_index = { path = "../index" }
rinx_toctree = { path = "../toctree" }
rinx_scope = { path = "../scope" }
serde_json = "1"

[lints]
workspace = true
