[package]
name = "rusty_sphinx_analyzer"
version = "0.1.0"
edition.workspace = true

[dependencies]
rusty_sphinx_ast = { path = "../ast" }
rusty_sphinx_entity = { path = "../entity" }
rusty_sphinx_index = { path = "../index" }
rusty_sphinx_toctree = { path = "../toctree" }
rusty_sphinx_scope = { path = "../scope" }
serde_json = "1"

[lints]
workspace = true
