load("@crates//:defs.bzl", "all_crate_deps")
load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_library")

rust_library(
    name = "rinx_lib",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "rinx",
    edition = "2024",
    deps = all_crate_deps(
        normal = True,
    ) + [
        "//crates/analyzer:rinx_analyzer",
        "//crates/ast:rinx_ast",
        "//crates/entity:rinx_entity",
        "//crates/inventory:rinx_inventory",
        "//crates/lsp:rinx_lsp",
        "//crates/toctree:rinx_toctree",
        "//crates/parser:rinx_parser",
        "//crates/renderer:rinx_renderer",
    ],
)

rust_binary(
    name = "rinx",
    srcs = glob(["src/**/*.rs"]),
    edition = "2024",
    visibility = ["//visibility:public"],
    deps = all_crate_deps(
        normal = True,
    ) + [
        ":rinx_lib",
        "//crates/analyzer:rinx_analyzer",
        "//crates/ast:rinx_ast",
        "//crates/entity:rinx_entity",
        "//crates/toctree:rinx_toctree",
        "//crates/index:rinx_index",
        "//crates/inventory:rinx_inventory",
        "//crates/lsp:rinx_lsp",
        "//crates/parser:rinx_parser",
        "//crates/renderer:rinx_renderer",
    ],
)
