[workspace]
resolver = "2"
members = ["crates/cdecl", "crates/filter", "crates/ast", "crates/scope",
    "crates/toctree", "crates/entity", "crates/index", "crates/parser", "crates/analyzer", "crates/renderer", "crates/worker"]

[workspace.package]
edition = "2024"

[workspace.lints.clippy]
pedantic = "warn"

[workspace.lints.rust]
unsafe_code = "forbid"
