[package]
name = "rusty_sphinx_index"
version = "0.1.0"
edition.workspace = true

[dependencies]
rusty_sphinx_ast = { path = "../ast" }
rusty_sphinx_entity = { path = "../entity" }
rusty_sphinx_filter = { path = "../filter" }
pathdiff = "0.2"
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
serde_json = "1"

[lints]
workspace = true
