//! The `diagnostic_codes_rst` subcommand: prints the documentation page
//! listing every diagnostic code.
//!
//! Exists so the checked-in `docs/diagnostics.rst` is generated from
//! [`DiagnosticCode::ALL`] and each code's doc comment, rather than kept in
//! step by hand: a test below compares the two, so a code added without
//! regenerating the page fails. The language server links each diagnostic to
//! its code's section, by the id [`rinx_ast::section_slug`] gives the heading.
//!
//! Like `entity_json_schema`, it is developer tooling: no Bazel rule runs it,
//! and it reads nothing.

use std::fmt::Write as _;

use rinx_ast::DiagnosticCode;

/// What the page says before the first code.
const INTRODUCTION: &str = "\
.. _diagnostics:

Diagnostic codes
================

.. Generated by `rinx diagnostic_codes_rst` from the doc comments in
   crates/ast/src/diagnostic_code.rs. Edit those, then regenerate.

Every problem rinx finds carries a stable code. The build prints it in each
warning::

   warning: guide/intro.rst:42:18: link.broken-ref: broken ref 'missing'

and the language server shows it on each underline, linked to its section
here. A ``.. noqa:`` comment naming codes silences them for the block that
follows it::

   .. noqa: link.broken-ref

   See :ref:`missing`.

Codes are grouped by the construct they concern. Once a code is written in a
``.. noqa:``, it is part of that document, so a code is never renamed lightly.
";

/// The page. Pure, so the tests below need no process.
pub(super) fn process_diagnostic_codes_rst() -> String {
    let mut page = INTRODUCTION.to_string();
    let mut current_group = None;
    for &code in DiagnosticCode::ALL {
        let group = code_group(code);
        if current_group != Some(group) {
            current_group = Some(group);
            let _ = write!(page, "\n{group}\n{}\n", "-".repeat(group.chars().count()));
        }
        let id = code.as_str();
        let _ = write!(
            page,
            "\n{id}\n{}\n\n{}",
            "~".repeat(id.chars().count()),
            description_rst(code.description())
        );
    }
    page
}

/// Writes the page to stdout.
///
/// Returns nothing rather than `Result<()>`, for the reason
/// `cmd_entity_json_schema` does: it reads nothing, so it cannot fail.
pub(crate) fn cmd_diagnostic_codes_rst() {
    print!("{}", process_diagnostic_codes_rst());
}

/// The construct `code` concerns: its id up to the first dot.
fn code_group(code: DiagnosticCode) -> &'static str {
    let id = code.as_str();
    id.split_once('.').map_or(id, |(group, _)| group)
}

/// The width the page's paragraphs are wrapped to.
const LINE_WIDTH: usize = 79;

/// A code's doc comment as reStructuredText: one wrapped paragraph per
/// blank-line separated block, separated by blank lines.
fn description_rst(description: &str) -> String {
    let mut paragraphs = Vec::new();
    let mut paragraph: Vec<&str> = Vec::new();
    for line in description.lines().chain(std::iter::once("")) {
        let line = line.trim();
        if line.is_empty() {
            if !paragraph.is_empty() {
                paragraphs.push(wrap(&inline_rst(&paragraph.join(" ")), LINE_WIDTH));
                paragraph.clear();
            }
        } else {
            paragraph.push(line);
        }
    }
    let mut text = paragraphs.join("\n\n");
    text.push('\n');
    text
}

/// `text` broken into lines of at most `width` characters where it can be.
///
/// Never breaks inside an inline literal, nor after the backslash of an
/// escaped space: either would change what the line means.
fn wrap(text: &str, width: usize) -> String {
    let mut words: Vec<String> = Vec::new();
    for word in text.split(' ') {
        match words.last_mut() {
            Some(last) if last.ends_with('\\') || last.matches("``").count() % 2 == 1 => {
                last.push(' ');
                last.push_str(word);
            }
            _ => words.push(word.to_string()),
        }
    }
    let mut lines: Vec<String> = Vec::new();
    for word in words {
        match lines.last_mut() {
            Some(line) if line.chars().count() + 1 + word.chars().count() <= width => {
                line.push(' ');
                line.push_str(&word);
            }
            _ => lines.push(word),
        }
    }
    lines.join("\n")
}

/// One paragraph of rustdoc Markdown as reStructuredText.
///
/// Converts the two constructs the codes' doc comments use whose spelling
/// differs: a code span (`` `x` `` becomes ``` ``x`` ```) and an intra-doc
/// link to another code (``[`Self::IncludeCycle`]`` becomes that code's id).
/// Emphasis is spelled the same in both.
fn inline_rst(markdown: &str) -> String {
    let mut out = String::new();
    let mut rest = markdown;
    while let Some(start) = rest.find(['`', '[']) {
        let (before, from) = rest.split_at(start);
        out.push_str(before);
        if let Some((id, after)) = intra_doc_link(from) {
            push_literal(&mut out, id, after);
            rest = after;
        } else if let Some((content, after)) = code_span(from) {
            push_literal(&mut out, content, after);
            rest = after;
        } else {
            let mut chars = from.chars();
            out.extend(chars.next());
            rest = chars.as_str();
        }
    }
    out.push_str(rest);
    out
}

/// The id of the code an intra-doc link at the start of `text` names, and
/// the text after the link.
fn intra_doc_link(text: &str) -> Option<(&'static str, &str)> {
    let inner = text.strip_prefix("[`Self::")?;
    let (variant, after) = inner.split_once("`]")?;
    let code = DiagnosticCode::ALL
        .iter()
        .find(|code| format!("{code:?}") == variant)?;
    Some((code.as_str(), after))
}

/// The content of the Markdown code span at the start of `text`, and the
/// text after it. A run of backticks closes at the next run of the same
/// length — Markdown's rule, which lets a span hold a backtick.
///
/// The content is trimmed, where Markdown drops at most one space a side:
/// a reStructuredText literal may neither start nor end with whitespace.
fn code_span(text: &str) -> Option<(&str, &str)> {
    let fence_len = text.chars().take_while(|&c| c == '`').count();
    if fence_len == 0 {
        return None;
    }
    let fence = &text[..fence_len];
    let body = &text[fence_len..];
    let mut search_from = 0;
    loop {
        let close = search_from + body[search_from..].find(fence)?;
        let run = body[close..].chars().take_while(|&c| c == '`').count();
        if run == fence_len {
            return Some((body[..close].trim(), &body[close + fence_len..]));
        }
        search_from = close + run;
    }
}

/// Appends `content` as an inline literal.
///
/// reStructuredText only recognizes inline markup between word boundaries,
/// so a literal touching a letter on either side (`` `x`s ``) is separated
/// by an escaped space, which renders as nothing.
fn push_literal(out: &mut String, content: &str, after: &str) {
    if out.chars().next_back().is_some_and(char::is_alphanumeric) {
        out.push_str("\\ ");
    }
    out.push_str("``");
    out.push_str(content);
    out.push_str("``");
    if after.chars().next().is_some_and(char::is_alphanumeric) {
        out.push_str("\\ ");
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::Path;

    use rinx_ast::{SectionId, allocate_section_ids, section_slug};

    fn checked_in_page() -> String {
        let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../docs/diagnostics.rst");
        std::fs::read_to_string(path).expect("docs/diagnostics.rst is readable")
    }

    #[test]
    fn test_the_checked_in_page_is_up_to_date() {
        // Given / When
        let generated = process_diagnostic_codes_rst();

        // Then
        assert!(
            generated == checked_in_page(),
            "docs/diagnostics.rst is stale; regenerate it with \
             `cargo run -p rinx -- diagnostic_codes_rst > docs/diagnostics.rst`"
        );
    }

    #[test]
    fn test_the_page_parses_without_a_diagnostic() {
        // Given / When
        let document = rinx_parser::parse("diagnostics.rst", &process_diagnostic_codes_rst());

        // Then
        assert_eq!(document.diagnostics, Vec::new());
    }

    #[test]
    fn test_every_code_has_the_section_id_the_server_links_to() {
        // Given
        let document = rinx_parser::parse("diagnostics.rst", &process_diagnostic_codes_rst());

        // When
        let ids: Vec<String> = allocate_section_ids(&document.nodes)
            .into_values()
            .map(|id: SectionId| id.as_str().to_string())
            .collect();

        // Then — a duplicate slug would be renamed, and its link would miss
        let missing: Vec<&str> = DiagnosticCode::ALL
            .iter()
            .map(|code| code.as_str())
            .filter(|id| !ids.contains(&section_slug(id)))
            .collect();
        assert_eq!(missing, Vec::<&str>::new());
    }

    #[test]
    fn test_the_page_lists_each_code_under_its_group() {
        // Given / When
        let page = process_diagnostic_codes_rst();

        // Then
        assert!(page.contains(
            "\nlink\n----\n\nlink.broken-ref\n~~~~~~~~~~~~~~~\n\n\
             A ``:ref:`` whose label is in no document's index.\n"
        ));
    }

    #[test]
    fn test_code_group_is_the_id_before_the_first_dot() {
        // Given / When / Then
        assert_eq!(code_group(DiagnosticCode::TableGridNoRows), "table");
        assert_eq!(code_group(DiagnosticCode::LinkBrokenRef), "link");
    }

    #[test]
    fn test_description_rst_keeps_paragraphs_apart() {
        // Given
        let description = " First line\n of one.\n\n Second.\n";

        // When / Then
        assert_eq!(
            description_rst(description),
            "First line of one.\n\nSecond.\n"
        );
    }

    #[test]
    fn test_wrap_breaks_between_words_at_the_width() {
        // Given / When / Then
        assert_eq!(wrap("aaa bbb ccc", 7), "aaa bbb\nccc");
    }

    #[test]
    fn test_wrap_keeps_a_literal_and_an_escape_whole() {
        // Given / When / Then
        assert_eq!(wrap("a ``b c`` d", 3), "a\n``b c``\nd");
        assert_eq!(wrap("x\\ ``y``", 2), "x\\ ``y``");
    }

    #[test]
    fn test_inline_rst_converts_a_code_span() {
        // Given / When / Then
        assert_eq!(inline_rst("a `:ref:` role"), "a ``:ref:`` role");
    }

    #[test]
    fn test_inline_rst_converts_a_padded_double_backtick_span() {
        // Given / When / Then
        assert_eq!(
            inline_rst("as ``:ref:`x`_ ``, shown"),
            "as ``:ref:`x`_``, shown"
        );
    }

    #[test]
    fn test_inline_rst_names_the_code_an_intra_doc_link_points_at() {
        // Given / When / Then
        assert_eq!(
            inline_rst("unlike [`Self::IncludeCycle`]: deep"),
            "unlike ``include.cycle``: deep"
        );
    }

    #[test]
    fn test_inline_rst_separates_a_literal_touching_a_word() {
        // Given / When / Then
        assert_eq!(inline_rst("`id`s"), "``id``\\ s");
        assert_eq!(inline_rst("x`id`"), "x\\ ``id``");
    }

    #[test]
    fn test_inline_rst_leaves_an_unclosed_backtick_and_a_plain_bracket() {
        // Given / When / Then
        assert_eq!(inline_rst("a ` and [b]"), "a ` and [b]");
    }

    #[test]
    fn test_code_span_skips_a_longer_run_inside() {
        // Given / When / Then — a ``` run does not close a single-backtick span
        assert_eq!(code_span("`a```b` c"), Some(("a```b", " c")));
    }
}
