//! The `entity_json_schema` subcommand: prints the JSON Schema for a schema
//! file.
//!
//! Exists so the checked-in `schemas/entities.schema.json` is regenerated by
//! the same code that defines the format, rather than edited by hand. A test
//! in `rinx_entity` compares the two, so a `Raw*` type changed without
//! regenerating fails the build.
//!
//! Not part of the documentation pipeline: no Bazel rule runs it, and it reads
//! nothing. It is developer tooling, in the same spirit as the benchmark
//! script.

/// Prints the schema. Pure, so the test below needs no process.
pub(super) fn process_entity_json_schema() -> String {
    rinx_entity::entity_json_schema_text()
}

/// Writes the schema to stdout.
///
/// Returns nothing rather than `Result<()>` like its sibling subcommands: it
/// reads no files and validates nothing, so there is no failure to report and a
/// `Result` would only invite a pointless `?`.
pub(crate) fn cmd_entity_json_schema() {
    print!("{}", process_entity_json_schema());
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_the_output_is_a_json_object() {
        // Given / When
        let text = process_entity_json_schema();

        // Then
        let value: serde_json::Value =
            serde_json::from_str(&text).expect("the subcommand should print valid JSON");
        assert!(value.is_object());
    }

    #[test]
    fn test_the_output_ends_with_a_newline() {
        // Given — it is redirected into a checked-in text file
        let text = process_entity_json_schema();

        // When / Then
        assert!(text.ends_with('\n'));
    }
}
