[package]
name = "rinx_parser"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
rinx_ast = { path = "../ast" }
rinx_filter = { path = "../filter" }
rinx_entity = { path = "../entity" }
rinx_template = { path = "../template" }
csv = "1"
octicons-pack = { version = "19.33", default-features = false }
regex = "1.10"
unicode-width = "0.2"

[lints]
workspace = true
