[package]
name = "rusty_sphinx_parser"
version = "0.1.0"
edition.workspace = true

[dependencies]
rusty_sphinx_ast = { path = "../ast" }
rusty_sphinx_filter = { path = "../filter" }
rusty_sphinx_entity = { path = "../entity" }
csv = "1"
octicons-pack = { version = "19.33", default-features = false }
regex = "1.10"
unicode-width = "0.2"

[lints]
workspace = true
