load("@crates//:defs.bzl", "all_crate_deps")
load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "rinx_lsp",
    srcs = glob(["src/**/*.rs"]),
    edition = "2024",
    visibility = ["//visibility:public"],
    deps = all_crate_deps(
        normal = True,
    ) + [
        "//crates/analyzer:rinx_analyzer",
        "//crates/ast:rinx_ast",
        "//crates/entity:rinx_entity",
        "//crates/index:rinx_index",
        "//crates/parser:rinx_parser",
        "//crates/renderer:rinx_renderer",
        "//crates/toctree:rinx_toctree",
    ],
)
