[package]
name = "rusty_sphinx_uml"
version = "0.1.0"
edition.workspace = true

[dependencies]
rusty_sphinx_ast = { path = "../ast" }
rusty_sphinx_entity = { path = "../entity" }
rusty_sphinx_filter = { path = "../filter" }
rusty_sphinx_index = { path = "../index" }
minijinja = "2"

[lints]
workspace = true
